### ISSUE TITLE
Question: How do you configure the types/categories?

### ISSUE THREAD

**Issue by theinventor** [TheSin-/notificationcenter#1]
How do you configure the "types" colors/icons/etc for the side panel?

(calendar/gift/fontawesome/etc)

**Comment by TheSin-** [comment]
http://thesin-.github.io/notificationcenter/#params

click on types.

Also if you view source on that page you'll see examples though I hope to dock is enough to explain it.  Let me know if you still have problems.

**Comment by theinventor** [comment]
Hah- sorry, thank you :)

Troy Anderson

**Comment by TheSin-** [comment]
no problem at all, glad you got it sorted.
