### ISSUE TITLE
Clicking doesn't close the notification like the demo

### ISSUE THREAD

**Issue by saleh-old** [TheSin-/notificationcenter#2]
Hi
I have implemented the lib in a project of mine, it works fine except one quick problem.
After clicking on an alert notification it gets closed but it comes back again! until the display_time is over. 
Any idea how to fix it? 
Thanks

**Comment by TheSin-** [comment]
oh that is odd I do not have this issue, could you setup a demo some place? maybe jsfiddle?  I'd love to see it happen.

**Comment by saleh-old** [comment]
Never mind, I just found out about the web notifications! It's much better for my case. 
I don't think there is a need for these kind of plugins anymore. 
Thank you

**Comment by TheSin-** [comment]
no problem sorry we couldn't solve your issue for you.

For me I personally do not want use web notifications, so I do see a need for it. But I agree it's all based not he designers needs.
